import "server-only";
import { mkdir, writeFile, stat, unlink, readFile } from "node:fs/promises";
import path from "node:path";
import type { Locale } from "@/lib/i18n";
import { renderTrainingPdf, renderNutritionPdf } from "./render-course";

/**
 * Generated course PDFs are written to disk so they can be attached to a
 * WhatsApp message and served without re-rendering. Kept outside /public —
 * the only way in is the share token.
 */
export function coursesDir(): string {
  return process.env.COURSE_PDF_DIR || "./storage/courses";
}

export type CourseKind = "training" | "nutrition";

export function coursePdfPath(shareToken: string): string {
  // The token is generated by nanoid, but basename() keeps a hand-crafted
  // value from escaping the directory.
  return path.join(coursesDir(), `${path.basename(shareToken)}.pdf`);
}

export function coursePdfFilename(kind: CourseKind, memberName: string): string {
  const base = kind === "training" ? "training" : "nutrition";
  const safe = memberName.replace(/[\\/:*?"<>|]/g, "").trim().replace(/\s+/g, "-");
  return `${base}-${safe || "course"}.pdf`;
}

/** Render a course and store it. Returns the absolute path on disk. */
export async function saveCoursePdf(opts: {
  kind: CourseKind;
  id: string;
  shareToken: string;
  locale: Locale;
  baseUrl: string;
}): Promise<string | null> {
  const bytes =
    opts.kind === "training"
      ? await renderTrainingPdf(opts.id, opts.locale, opts.baseUrl)
      : await renderNutritionPdf(opts.id, opts.locale);
  if (!bytes) return null;

  await mkdir(coursesDir(), { recursive: true });
  const file = coursePdfPath(opts.shareToken);
  await writeFile(file, Buffer.from(bytes));
  return path.resolve(file);
}

/** Read a stored PDF, or null when it was never generated / was cleaned up. */
export async function readCoursePdf(shareToken: string): Promise<Buffer | null> {
  const file = coursePdfPath(shareToken);
  try {
    await stat(file);
    return await readFile(file);
  } catch {
    return null;
  }
}

export async function deleteCoursePdf(shareToken: string) {
  try {
    await unlink(coursePdfPath(shareToken));
  } catch {
    // Already gone.
  }
}
