-- AlterTable
ALTER TABLE `activitylog` MODIFY `action` ENUM('REGISTER_MEMBER', 'UPDATE_MEMBER', 'DELETE_MEMBER', 'RENEW_SUBSCRIPTION', 'RECEIVE_PAYMENT', 'FREEZE_SUBSCRIPTION', 'UNFREEZE_SUBSCRIPTION', 'CANCEL_SUBSCRIPTION', 'CREATE_PLAN', 'UPDATE_PLAN', 'ARCHIVE_PLAN', 'CREATE_TRAINING_COURSE', 'CREATE_NUTRITION_COURSE', 'SAVE_TEMPLATE', 'UPDATE_TEMPLATE', 'DELETE_TEMPLATE', 'ADD_VIDEO', 'EDIT_VIDEO', 'DELETE_VIDEO', 'CREATE_USER', 'UPDATE_USER', 'TOGGLE_VIDEO_PERMISSION', 'CREATE_EXPENSE', 'DELETE_EXPENSE', 'CREATE_DEBT', 'RECEIVE_DEBT_PAYMENT', 'DELETE_DEBT', 'CREATE_BACKUP', 'RESTORE_BACKUP', 'SEND_COURSE') NOT NULL;

-- AlterTable
ALTER TABLE `trainingcourse` ADD COLUMN `sentTo` VARCHAR(191) NULL,
    ADD COLUMN `sentAt` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `nutritioncourse` ADD COLUMN `sentTo` VARCHAR(191) NULL,
    ADD COLUMN `sentAt` DATETIME(3) NULL;
